export const GET_USER = 'GET_USER'

export const SET_USER = 'SET_USER'

export const RESET_USER = 'RESET_USER'

export const GET_GOOGLE_USER = 'GET_GOOGLE_USER'

export const IS_LOGIN = 'IS_LOGIN'

export const DELETE_USER = 'DELETE_USER'

export const SET_ADMIN = 'SET_ADMIN'

export const REMOVE_ADMIN = 'REMOVE_ADMIN'

export const BLOCK_USER = 'BLOCK_USER'

export const UNBLOCK_USER = 'UNBLOCK_USER'

export const SET_ERROR = 'SET_ERROR'

export const CLEAR_ERROR = 'CLEAR_ERROR'

export const SET_ITEM = 'SET_ITEM'

export const GET_ITEM = 'GET_ITEM'

export const GET_COLLECTION = 'GET_COLLECTION'

export const SORT_COLLECTION = 'SORT_COLLECTION'

export const CHANGE_ASCENDING = 'CHANGE_ASCENDING'

export const GET_HOME = 'GET_HOME'

export const SET_SEARCH = 'SET_SEARCH'

export const SWITCH_LANG = 'SWITCH_LANG'

export const GET_ALLCOLLECTIONS = 'GET_ALLCOLLECTIONS'

export const START_LOADING_PAGE = 'START_LOADING_PAGE'

export const END_LOADING_PAGE = 'END_LOADING_PAGE'

export const SET_NOTIFY = 'SET_NOTIFY'

export const ERROR_CLEARALL = 'ERROR_CLEARALL'

export const START_LOADING_COLLECTIONS = 'START_LOADING_COLLECTIONS' 

export const END_LOADING_COLLECTIONS = 'END_LOADING_COLLECTIONS' 

export const START_LOADING_COLLECTION = 'START_LOADING_COLLECTION' 

export const END_LOADING_COLLECTION = 'END_LOADING_COLLECTION' 